### ISSUE TITLE
Command injection in arguments

### ISSUE THREAD

**Issue by csalazar** [niclabs/gitman#1]
Hi guys, both arguments `token` and `org` aren't sanitized correctly making possible to execute arbitrary commands on the machine that runs/serves *gitman*. Below I attach two examples at command line that create the file `/tmp/hola`. Obviously it also affects *gitman* running via web.

* `php gitman.php '" http://nic.cl ; touch /tmp/hola; #' org`
* `php gitman.php 123 '123 ; touch /tmp/hola; #'`

**Comment by madestro** [comment]
Thanks, the idea was to run gitman locally, but yes you are right.
